# Generated by Django 4.2.1 on 2023-11-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('matricula', models.CharField(max_length=255)),
                ('senha', models.CharField(default='Aluno@ifpi', max_length=255)),
                ('tipo', models.CharField(default='aluno', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=15)),
                ('dataCriacao', models.DateField()),
                ('dataExpiracao', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroConsulta', models.IntegerField()),
                ('horario', models.IntegerField()),
                ('data', models.DateField()),
                ('pendente', models.BooleanField(default=True)),
                ('estevePresente', models.BooleanField(default=False)),
                ('descricao', models.TextField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.usuario')),
            ],
        ),
    ]
